# Generated by Django 6.0 on 2025-12-31 20:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('decade', models.CharField(blank=True, max_length=10)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('poster_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['title'], name='storylovers_title_e3bb8a_idx'), models.Index(fields=['director'], name='storylovers_directo_d8a25f_idx'), models.Index(fields=['year'], name='storylovers_year_9f8bf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField(help_text='Weight as percentage (5-50). All categories should sum to 100.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='storylovers.rubric')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('rubric', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StoryLover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('podcast_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_lover', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storylovers',
            },
        ),
        migrations.AddField(
            model_name='rubric',
            name='story_lover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='storylovers.storylover'),
        ),
        migrations.CreateModel(
            name='FilmLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('warm', 'Warm'), ('melancholy', 'Melancholy'), ('thrilled', 'Thrilled'), ('reflective', 'Reflective'), ('joyful', 'Joyful'), ('unsettled', 'Unsettled'), ('dreamy', 'Dreamy'), ('profound', 'Profound')], max_length=20)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('is_new_director', models.BooleanField(default=False)),
                ('is_rewatch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='storylovers.film')),
                ('story_lover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_logs', to='storylovers.storylover')),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='storylovers.rubriccategory')),
                ('film_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_ratings', to='storylovers.filmlog')),
            ],
            options={
                'unique_together': {('film_log', 'category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='rubric',
            unique_together={('story_lover', 'name')},
        ),
        migrations.AddIndex(
            model_name='filmlog',
            index=models.Index(fields=['story_lover', '-watched_at'], name='storylovers_story_l_892f44_idx'),
        ),
        migrations.AddIndex(
            model_name='filmlog',
            index=models.Index(fields=['story_lover', 'film'], name='storylovers_story_l_a9f75a_idx'),
        ),
    ]
