# Generated by Django 6.0 on 2026-01-11 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylovers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Film Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilmDirector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='film',
            name='storylovers_directo_d8a25f_idx',
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='films', to='storylovers.filmcountry'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='films', to='storylovers.filmdirector'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='storylovers.filmgenre'),
        ),
        migrations.AddField(
            model_name='film',
            name='story_locations',
            field=models.ManyToManyField(blank=True, related_name='films', to='storylovers.storylocation'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
